### ISSUE TITLE
Experiment about 3DMatch?

### ISSUE THREAD

**Issue by Codefmeister** [fukexue/RGM#7]
3DMatch test dataset offered officially is fragments contains ply data. But I noticed that you load the numpy directly using np.load() according to your code.
How did you do the preprocessing work?

**Comment by fukexue** [comment]
sorry, 

I just saw that if you still need it, I can send the processed files to you. The data I use is the code from the article "deep global registration". 










--

Medical Image Computing and Computer Assisted Intervention(MICCAI), Fudan University
No. 331 Dong'an Road, Shanghai 200433, China
Tel.：19921895251
Email: ***@***.******@***.***




At 2021-09-02 10:30:00, "Jinqian Chen" ***@***.***> wrote:

3DMatch test dataset offered officially is fragments contains ply data. But I noticed that you load the numpy directly using np.load() according to your code.
How did you do the preprocessing work?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
